columnSuffix: tzvpmbrm
contentColumnType: string(400)
fieldGroup: 54a3e6eb-0887-4880-a798-4bf78095795c # Meta
handle: pageTitle
instructions: null
name: 'Page title'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
