fieldLayouts:
  ef6432a7-e2f8-45e5-930d-0cee96b22bea:
    tabs:
      -
        elements:
          -
            fieldUid: 4f9488d6-5cba-4c4b-9126-4f6370d90690 # Page title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7215f315-e5c6-4519-aeb5-ea17a92d5c17
            warning: null
            width: 100
          -
            fieldUid: a29fa51b-961a-4881-b4b5-c3e066122601 # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5c7adc8-2f5d-44fd-9228-6b98b284922c
            warning: null
            width: 100
          -
            fieldUid: e6ea26c6-b576-4b94-8b94-222e4396c11a # Meta keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77bbd686-6fc5-4d7e-a769-9cfb6771a6f4
            warning: null
            width: 100
        name: Header
        uid: f4dba190-5dfe-4bdc-9abb-4e8678f57422
handle: header
name: Header
sortOrder: 1
